# Generated by Django 3.1.5 on 2021-02-02 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210203_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 3, 3, 20, 51, 371595)),
        ),
    ]
