# Generated by Django 3.1.5 on 2021-02-03 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210203_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 3, 11, 27, 34, 149945)),
        ),
        migrations.AlterField(
            model_name='product',
            name='discription',
            field=models.TextField(null=True),
        ),
    ]
